// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtOmT-yEBru6tJb187odzn1ZUk94LePmA',
    appId: '1:392901481523:web:d868d97636f72d3f3aff46',
    messagingSenderId: '392901481523',
    projectId: 'test-33f86',
    authDomain: 'test-33f86.firebaseapp.com',
    storageBucket: 'test-33f86.appspot.com',
    measurementId: 'G-H3QVYZ3JXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDWCQSo9pISNfUjSQbBSLpt75NnIx-pJ0',
    appId: '1:392901481523:android:e25e32c670bec6903aff46',
    messagingSenderId: '392901481523',
    projectId: 'test-33f86',
    storageBucket: 'test-33f86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtIgZMiVkX-aHYCyR0bmhwpj1vEtK5DQw',
    appId: '1:392901481523:ios:0917c9a2a64564693aff46',
    messagingSenderId: '392901481523',
    projectId: 'test-33f86',
    storageBucket: 'test-33f86.appspot.com',
    iosBundleId: 'com.example.mission1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtIgZMiVkX-aHYCyR0bmhwpj1vEtK5DQw',
    appId: '1:392901481523:ios:5ed70e9de53681173aff46',
    messagingSenderId: '392901481523',
    projectId: 'test-33f86',
    storageBucket: 'test-33f86.appspot.com',
    iosBundleId: 'com.example.mission1.RunnerTests',
  );
}
